replicaCount: 3

image:
  repository: dockersamples/example-voting-app
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"

db:
  enabled: true

redis:
  enabled: true

worker:
  enabled: true

# Additional configurations as needed...
