replicaCount: 1

image:
  repository: dockersamples/example-voting-app
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: "200m"
    memory: "128Mi"
  requests:
    cpu: "100m"
    memory: "64Mi"

db:
  enabled: true

redis:
  enabled: true

worker:
  enabled: true

# Additional configurations as needed...
