apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "voting-app.labels" . | nindent 4 }}
    app: db
  name: db
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - image: {{ .Values.db.image }}
        name: postgres
        env:
        - name: POSTGRES_USER
          value: {{ .Values.db.username }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.db.password }}
        ports:
        - containerPort: {{ .Values.db.port }}
          name: postgres
        volumeMounts:
        - mountPath: {{ .Values.db.volume.mountPath }}
          name: db-data
      volumes:
      - name: db-data
        emptyDir: {}