apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "voting-app.labels" . | nindent 4 }}
    app: db
  name: db
spec:
  type: ClusterIP
  ports:
  - name: "db-service"
    port: {{ .Values.db.port }}
    targetPort: {{ .Values.db.port }}
  selector:
    app: db