apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "voting-app.labels" . | nindent 4 }}
    app: result
  name: result
spec:
  type: {{ .Values.result.service.type }}
  ports:
  - name: "result-service"
    port: {{ .Values.result.service.port }}
    targetPort: {{ .Values.result.port }}
    nodePort: {{ .Values.result.service.nodePort }}
  selector:
    app: result