apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "voting-app.labels" . | nindent 4 }}
    app: worker
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - image: {{ .Values.worker.image }}
        name: worker